Numpy- Part one 

In [4]:
import numpy as np 
np.version

import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [14]:
import numpy as np 
np.__version__

# my_list = ["naveed ", 12 ]
# print(type(my_list))
my_list = [1,2,3,4,5]
print(my_list)

arr1 = np.array(my_list)
print(type(arr1))

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


In [15]:
list = [12,12,1,]
print(type(list))

arr1 = np.array(list)
print(arr1)
print(type(arr1))

<class 'list'>
[12 12  1]
<class 'numpy.ndarray'>


In [21]:
np.arange(10)
np.arange(10,20)

np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# np.arange(20,8) # first agrument should be always greater than the second one 
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
np.arange(-20, 8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [28]:
n = np.arange(1,100)
n


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
n = np.zeros(3)
print(type(n))

<class 'numpy.ndarray'>


In [31]:
np.zeros(3, dtype= int)

array([0, 0, 0])

array([0, 0, 0], dtype=object)

In [43]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [44]:
np.zeros((2, 3, 4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((9,9), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
np.ones(3, dtype = int)

array([1, 1, 1])

In [53]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
np.ones((10,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
np.ones((5,5,5), dtype= int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [58]:
nd1

NameError: name 'nd1' is not defined

In [ ]:
my_list = [1,2,3,4,5]
print(my_list)

arr1 = np.array(my_list)
print(type(arr1))


np.arange(10)
np.arange(10,20)

np.arange(10,51,5)

# np.arange(20,8) # first agrument should be always greater than the second one 
np.arange(8,20)

n = np.arange(1,100)
n

n = np.zeros(3)
print(type(n))

np.zeros(3, dtype= dict)

np.zeros((2, 3, 4))

np.zeros((9,9), dtype = int)

np.ones(3, dtype = int)

np.ones((5,5), dtype = int)

np.ones((5,5,5), dtype= int)

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
import numpy as np
np.random.rand(7,2)

np.random.rand(2)



array([0.34639666, 0.799423  ])

In [4]:
np.random.rand(2,3)

array([[0.0721293 , 0.44868409, 0.4335956 ],
       [0.65050493, 0.76699417, 0.65281667]])

In [ ]:
np.random.randint()

30556

In [11]:
np.random.randint(87)

75

In [15]:
# np.random.rand(2,3)
np.random.random((2,3))

array([[0.77154772, 0.69536112, 0.17142622],
       [0.7910393 , 0.67814437, 0.44658003]])

In [16]:
np.random.randint(2,35)

12

In [18]:
np.random.randint(2,50,10)

array([47, 41, 16, 33, 36, 20, 25, 48, 18, 45])

In [39]:
np.random.randint(10,100,(10,10))

array([[57, 55, 82, 80, 77, 24, 11, 32, 44, 41],
       [47, 45, 46, 90, 71, 23, 52, 23, 92, 36],
       [96, 55, 41, 11, 45, 11, 58, 39, 20, 34],
       [97, 46, 42, 48, 89, 31, 29, 75, 22, 21],
       [61, 13, 96, 85, 34, 31, 20, 66, 95, 82],
       [62, 56, 50, 21, 77, 78, 31, 35, 89, 77],
       [92, 64, 29, 47, 25, 67, 92, 62, 64, 77],
       [96, 37, 95, 63, 40, 38, 52, 19, 83, 17],
       [59, 60, 90, 12, 10, 80, 52, 33, 54, 89],
       [57, 11, 93, 77, 21, 76, 31, 89, 93, 55]])

In [40]:
m = np.random.randint(10,100,(10,10))
m

array([[15, 79, 59, 58, 41, 29, 16, 81, 21, 83],
       [35, 42, 20, 86, 57, 53, 27, 34, 58, 66],
       [34, 51, 64, 44, 50, 63, 37, 53, 18, 70],
       [40, 38, 90, 12, 21, 72, 38, 60, 67, 85],
       [18, 36, 75, 23, 26, 92, 86, 62, 89, 64],
       [52, 29, 55, 57, 32, 97, 67, 58, 74, 94],
       [93, 85, 45, 66, 35, 99, 91, 12, 27, 81],
       [56, 91, 22, 64, 84, 36, 16, 48, 26, 91],
       [14, 36, 21, 57, 19, 79, 18, 86, 42, 65],
       [58, 86, 48, 86, 66, 31, 28, 81, 13, 88]])

In [47]:
a = np.arange(1,15)
a.reshape(14,1)


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [ ]:

b = np.random.randint(10,15,(5,5))
# b[4:5]
print("full array is ",b)
print("array slicing is ", b[2:5])

full array is  [[10 14 11 14 12]
 [11 11 14 13 11]
 [11 14 13 11 10]
 [11 12 11 11 12]
 [13 11 12 11 12]]


NameError: name 'n' is not defined

In [67]:
m = np.arange(0,100,(10,10))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [68]:
brew install git

SyntaxError: invalid syntax (17741898.py, line 1)